### ISSUE TITLE
[Suggestion] Stiletto compatibility 

### ISSUE THREAD

**Issue by EveKaczmarek** [OrangeSpork/AdvIKPlugin#4]
Can you add a check for stiletto plugin installation? Default settings leads to stiletto break up and it's difficult to understand what plugin are responsible for this behavior. This check implemented in Maker Optimizations, something like this would be nice to see in yours plugin too.

**Comment by OrangeSpork** [comment]
I don't know what this is asking for exactly, check for stiletto and do what specifically?

**Comment by EveKaczmarek** [comment]
![Koikatu_20220402_063808_F982Gwh4sx](https://user-images.githubusercontent.com/52298587/161369023-948b8d84-c537-4f35-98fa-73acc4af56be.png)
![Koikatu_20220402_063841_QzDa7iKFB9](https://user-images.githubusercontent.com/52298587/161369025-2150524b-0f0b-4f5a-8254-e1f3aafe14b6.png)
These two options do almost the same job, the main difference between them is that AdvIK does not check for Stiletto installation so leaving this option turned on (as it by default) leads to issues with characters feet.

I suggest to disable this option by default or implement a checkup that will disable this option in case Stiletto plugin is installed.
